ignoreGeneratedHeader = true
severity = "warning"

[rule.blank-imports]
severity = "error"

[rule.context-as-argument]
severity = "error"

[rule.dot-imports]
severity = "error"

[rule.error-naming]
severity = "error"

[rule.error-return]
severity = "warning"

[rule.exported]
severity = "warning"

[rule.if-return]
severity = "warning"

[rule.increment-decrement]
severity = "warning"

[rule.var-naming]
arguments = ["camelCase"]
severity = "warning"

[rule.package-comments]
severity = "error"

[rule.argument-limit]
arguments = [5]
severity = "warning"

[rule.line-length-limit]
arguments = [120]
severity = "warning"

[rule.time-naming]
severity = "warning"

[rule.struct-tag]
severity = "warning"

[rule.unused-parameter]
severity = "warning"

[rule.unused-receiver]
severity = "warning"
