# SuiGraph Configuration
server:
  port: 8080
  host: "0.0.0.0"

sui:
  rpc_url: "https://fullnode.mainnet.sui.io:443"
  fetch_interval_sec: 5
  checkpoint_start: 100000

database:
  driver: "postgres"
  dsn: "host=localhost user=sui_graph dbname=sui_graph password=secret sslmode=disable"

dag:
  max_concurrency_layer: 10
  enable_shared_object_tracking: true

logging:
  level: "info"
