name: Changelog Reminder

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**
      - hotfix/**

jobs:
  check_changelog:
    name: Check Changelog Presence
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.8
        with:
          files_ignore: |
            **/*.md
            **/*_test.go
            tests/**
            **/*.py
            .github/workflows/**/*.yml

      - name: Run Changelog Check
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: meta:no-changelog
          checkNotification: Verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
